# Cleaning the Age Column

In [41]:
import pandas as pd
import numpy as np
import xlrd
import matplotlib.pyplot as plt
import seaborn as sns
import re

# Reading in Census Data

In [42]:
xls = pd.ExcelFile('data/Reservation Census.xlsx')
df_1900 = pd.read_excel(xls, '1900 Census')
df_1910 = pd.read_excel(xls, '1910 Census')
df_1920 = pd.read_excel(xls, '1920 Census')

## Preview of 1900 - 1920 Census Data

In [43]:
df_1900['Year'] = 1900
df_1910['Year'] = 1910
df_1920['Year'] = 1920
df_1900_rsac = df_1900[["Age at last birthday (8)",'Year']]
df_1910_rsac = df_1910[['Age at last birthday (8)','Year']]
df_1920_rsac = df_1920[["Age at last birthday (8)",'Year']]

In [44]:

df_1900_rsac.rename(columns={'Age at last birthday (8)': 'Age'}, inplace=True)
df_1900_rsac.head()

Age  Year
0  26  1900
1  27  1900
2  25  1900
3  25  1900
4   8  1900

## Preview of 1910 Census Data

In [45]:

df_1910_rsac.rename(columns={'Age at last birthday (8)': 'Age'}, inplace=True)
df_1910_rsac.head()

Age  Year
0  27  1910
1  23  1910
2  15  1910
3  28  1910
4  25  1910

## Preview of 1920 Census Data

In [46]:

df_1920_rsac.rename(columns={'Age at last birthday (8)': 'Age'}, inplace=True)
df_1920_rsac.head()

Age  Year
0              32  1920
1              27  1920
2               9  1920
3  5 and 0 months  1920
4               3  1920

In [47]:
#df_1900_rsac.dropna(inplace = True) 
df_1900_rsac.Age.unique()

array([26, 27, 25, 8, 46, 34, 19, 15, 12, 9, 21, 5, '1 month', 2, 58, 35,
       23, 18, 13, 56, 41, 20, 39, 7, 24, 51, 43, 17, 14, 60, '2 months',
       22, 54, 48, 10, 28, 30, 11, 32, 31, 29, 50, 49, 1, 63, 33, 6, 64,
       3, 37, 55, 36, 57, 53, 16, 87, 81, 38, 4, 65, 45, 40, 76,
       '5 months', 47, 44, 75, 42, '10 months', 52, 61, 68, 69, 77, 105,
       59, '4 months', 62, '11 months', nan, 84, 80], dtype=object)

In [48]:
#pd.to_numeric(df_1900_rsac.Age, errors='ignore').head()
df_1900_rsac["Age"] = df_1900_rsac["Age"].astype('str')
df_1910_rsac["Age"] = df_1910_rsac["Age"].astype('str')
df_1920_rsac["Age"] = df_1920_rsac["Age"].astype('str')

c:\users\user\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
c:\users\user\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
c:\users\user\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a Data

In [49]:


for i in range (0 ,len(df_1900_rsac.Age)):    
    num_list = [int(s) for s in re.findall(r'\b\d+\b', df_1900_rsac.Age[i])]

    if len(num_list) == 1:
        df_1900_rsac.Age[i] = round(num_list[0],1)
    elif len(num_list) == 2:
        df_1900_rsac.Age[i] = round((num_list[0] + (num_list[1]/12)),1)    
    else:
        df_1900_rsac.Age[i] = df_1900_rsac.Age[i]    


c:\users\user\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
c:\users\user\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()


In [50]:
df_1900_rsac.Age.unique()

array([26, 27, 25, 8, 46, 34, 19, 15, 12, 9, 21, 5, 1, 2, 58, 35, 23, 18,
       13, 56, 41, 20, 39, 7, 24, 51, 43, 17, 14, 60, 22, 54, 48, 10, 28,
       30, 11, 32, 31, 29, 50, 49, 63, 33, 6, 64, 3, 37, 55, 36, 57, 53,
       16, 87, 81, 38, 4, 65, 45, 40, 76, 47, 44, 75, 42, 52, 61, 68, 69,
       77, 105, 59, 62, 'nan', 84, 80], dtype=object)

In [51]:
for i in range (0 ,len(df_1920_rsac.Age)):    
    num_list = [int(s) for s in re.findall(r'\b\d+\b', df_1920_rsac.Age[i])]

    if len(num_list) == 1:
        df_1920_rsac.Age[i] = round(num_list[0],1)
    elif len(num_list) == 2:
        df_1920_rsac.Age[i] = round((num_list[0] + (num_list[1]/12)),1)     
    else:
        df_1920_rsac.Age[i] = df_1920_rsac.Age[i]    

c:\users\user\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
c:\users\user\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
c:\users\user\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


In [52]:
df_1920_rsac.Age.unique()

array([32, 27, 9, 5.0, 3, 2, 35, 26, 51, 23, 28, 43, 30, 31, 40, 33, 2.2,
       29, 62, 53, 21, 8, 5.1, 3.8, 11, 70, 80, 25, 13, 42, 39, 34, 38,
       19, 15, 3.9, 50, 45, 60, 65, 2.9, 47, 14, 17, 10, 52, 6, 1, 16, 24,
       5.9, 67, 44, 37, 22, 18, 55, 20, 54, 36, 48, 4.0, 'Un.', 7, 6.1,
       4.1, 2.5, 4.8, 1.3, 12, 57, 2.4, 61, 73, 56, 49, 2.8, 1.8, 41, 69,
       59, 46, 0, 3.2, 5.8, 3.5, 7.8, 3.7, 3.6, 71, 1.5, 3.4, 66, 3.3,
       1.9, 64, 90, 85, 68, 2.3, 1.4, 1.7, 63, 72, 75, 58, 4.2, 2.1, 4.4,
       76, 3.1, 2.7, 5.2, 92, 82, 4.6, 5.6, 83, 4.9, 5.3, 1.1, 100, 77,
       78, 5.4, 5.7, 5.5, 4.7, 74, 1.6, 4.3, 1.2, 4.5, 79], dtype=object)

15.4